name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install && DB_URL=${{ secrets.DB_URL }} npm run test